jadeVersionNumber "99.0.00";
schemaDefinition
CalculatorServicesClient subschemaOf RootSchema completeDefinition;
importedPackageDefinitions
	UserNameTokenSecurityProfile is WebServiceUtilitiesSchema::UserNameTokenSecurityProfile
	(
		documentationText
		`Package for Web Services Security`
	importedClassDefinitions
		JadeSecurityToken
		JadeUsernameToken
		JadeWSAddressingHeader
		JadeWSTimestampHeader
		JadeWebServicesSecurity
		Jadwssec
	)

localeDefinitions
	5129 "English (New Zealand)" schemaDefaultLocale;
typeHeaders
	Add subclassOf Object transient, transientAllowed, subclassTransientAllowed, webService, wsdlName = "add	urn:JadeWebServices/CalculatorService/";
	AddResponse subclassOf Object transient, transientAllowed, subclassTransientAllowed, webService, wsdlName = "addResponse	urn:JadeWebServices/CalculatorService/";
	CalculatorServicesClient subclassOf RootSchemaApp transient, sharedTransientAllowed, transientAllowed, subclassSharedTransientAllowed, subclassTransientAllowed;
	Divide subclassOf Object transient, transientAllowed, subclassTransientAllowed, webService, wsdlName = "divide	urn:JadeWebServices/CalculatorService/";
	DivideResponse subclassOf Object transient, transientAllowed, subclassTransientAllowed, webService, wsdlName = "divideResponse	urn:JadeWebServices/CalculatorService/";
	GCalculatorServicesClient subclassOf RootSchemaGlobal transient, sharedTransientAllowed, transientAllowed, subclassSharedTransientAllowed, subclassTransientAllowed;
	JadeCalculator subclassOf JadeWebServiceConsumer transient, transientAllowed, subclassTransientAllowed, webService;
	Multiply subclassOf Object transient, transientAllowed, subclassTransientAllowed, webService, wsdlName = "multiply	urn:JadeWebServices/CalculatorService/";
	MultiplyResponse subclassOf Object transient, transientAllowed, subclassTransientAllowed, webService, wsdlName = "multiplyResponse	urn:JadeWebServices/CalculatorService/";
	Subtract subclassOf Object transient, transientAllowed, subclassTransientAllowed, webService, wsdlName = "subtract	urn:JadeWebServices/CalculatorService/";
	SubtractResponse subclassOf Object transient, transientAllowed, subclassTransientAllowed, webService, wsdlName = "subtractResponse	urn:JadeWebServices/CalculatorService/";
	SCalculatorServicesClient subclassOf RootSchemaSession transient, sharedTransientAllowed, transientAllowed, subclassSharedTransientAllowed, subclassTransientAllowed;
membershipDefinitions
typeDefinitions
	UserNameTokenSecurityProfile::JadeSecurityToken completeDefinition
	(
	)
	UserNameTokenSecurityProfile::JadeUsernameToken completeDefinition
	(
	)
	UserNameTokenSecurityProfile::JadeWSAddressingHeader completeDefinition
	(
	)
	UserNameTokenSecurityProfile::JadeWSTimestampHeader completeDefinition
	(
	)
	UserNameTokenSecurityProfile::JadeWebServicesSecurity completeDefinition
	(
	)
	UserNameTokenSecurityProfile::Jadwssec completeDefinition
	(
	)
	JadeDotNetType completeDefinition
	(
	)
	Object completeDefinition
	(
	)
	Add completeDefinition
	(
		documentationText
`
    This class was generated by Jade.
     Runtime Version: 6.3

     Changes to this class may cause incorrect behavior and will be lost if 
     the class is regenerated. `
	attributeDefinitions
		a:                             Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:a", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
		b:                             Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:b", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
	)
	AddResponse completeDefinition
	(
		documentationText
`
    This class was generated by Jade.
     Runtime Version: 6.3

     Changes to this class may cause incorrect behavior and will be lost if 
     the class is regenerated. `
	attributeDefinitions
		addResult:                     Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:addResult", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
	)
	Application completeDefinition
	(
	)
	RootSchemaApp completeDefinition
	(
	)
	CalculatorServicesClient completeDefinition
	(
	)
	Divide completeDefinition
	(
		documentationText
`
    This class was generated by Jade.
     Runtime Version: 6.3

     Changes to this class may cause incorrect behavior and will be lost if 
     the class is regenerated. `
	attributeDefinitions
		a:                             Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:a", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
		b:                             Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:b", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
	)
	DivideResponse completeDefinition
	(
		documentationText
`
    This class was generated by Jade.
     Runtime Version: 6.3

     Changes to this class may cause incorrect behavior and will be lost if 
     the class is regenerated. `
	attributeDefinitions
		divideResult:                  Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:divideResult", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
	)
	Global completeDefinition
	(
	)
	RootSchemaGlobal completeDefinition
	(
	)
	GCalculatorServicesClient completeDefinition
	(
	)
	JadeScript completeDefinition
	(
	jadeMethodDefinitions
		testCalculator();
	)
	JadeWebService completeDefinition
	(
	webServicesClassProperties
	(
		wsdl = ``;
	)
	)
	JadeWebServiceConsumer completeDefinition
	(
	webServicesClassProperties
	(
		additionalInfo = ``;
		wsdl = ``;
		endPointURL = "";
		wsdlName = "";
		_useSOAP12 = false;
		useAsyncCalls = false;
		useNewPrimTypes = false;
	)
	)
	JadeCalculator completeDefinition
	(
	webServicesClassProperties
	(
		additionalInfo = `http=http://schemas.xmlsoap.org/wsdl/http/
soap=http://schemas.xmlsoap.org/wsdl/soap/
xsd=http://www.w3.org/2001/XMLSchema
tns=urn:JadeWebServices/CalculatorService/
mime=http://schemas.xmlsoap.org/wsdl/mime/
wsdl=http://schemas.xmlsoap.org/wsdl/
s1=http://jadeworld.com/wsdl/types/
targetNamespace=urn:JadeWebServices/CalculatorService/
*1=urn:JadeWebServices/CalculatorService/
`;
		wsdl = `D:\temp\CalculatorService.wsdl`;
		endPointURL = "http://cnwcrs1a/jade/jadehttp.dll?CalculatorServices&serviceName=JadeCalculator&listName=CalculatorService";
		wsdlName = "JadeCalculator";
		_useSOAP12 = false;
		useAsyncCalls = false;
		useNewPrimTypes = false;
	)
	jadeMethodDefinitions
		create() updating;
		getSoapAction(methodName: String): String;
		invoke(inputMessage: String): String updating;
	webServicesMethodDefinitions
		add(parameters: Add): AddResponse updating, webService, wsdlName = "add";
		webServicesMethodProperties
		(
			inputEncodingStyle = "";
			inputNamespace = "";
			inputUsesEncodedFormat = false;
			outputEncodingStyle = "";
			outputNamespace = "";
			outputUsesEncodedFormat = false;
			soapAction = "urn:JadeWebServices/CalculatorService/add";
			useBareStyle = false;
			useSoap12 = false;
			usesRPC = default;
			wsdlName = "add";
			soapHeaders = null;
		)
		divide(parameters: Divide): DivideResponse updating, webService, wsdlName = "divide";
		webServicesMethodProperties
		(
			inputEncodingStyle = "";
			inputNamespace = "";
			inputUsesEncodedFormat = false;
			outputEncodingStyle = "";
			outputNamespace = "";
			outputUsesEncodedFormat = false;
			soapAction = "urn:JadeWebServices/CalculatorService/divide";
			useBareStyle = false;
			useSoap12 = false;
			usesRPC = default;
			wsdlName = "divide";
			soapHeaders = null;
		)
		multiply(parameters: Multiply): MultiplyResponse updating, webService, wsdlName = "multiply";
		webServicesMethodProperties
		(
			inputEncodingStyle = "";
			inputNamespace = "";
			inputUsesEncodedFormat = false;
			outputEncodingStyle = "";
			outputNamespace = "";
			outputUsesEncodedFormat = false;
			soapAction = "urn:JadeWebServices/CalculatorService/multiply";
			useBareStyle = false;
			useSoap12 = false;
			usesRPC = default;
			wsdlName = "multiply";
			soapHeaders = null;
		)
		raiseSecurityTokenException(msg: String) webService;
		webServicesMethodProperties
		(
			inputEncodingStyle = "";
			inputNamespace = "";
			inputUsesEncodedFormat = false;
			outputEncodingStyle = "";
			outputNamespace = "";
			outputUsesEncodedFormat = false;
			soapAction = "";
			useBareStyle = false;
			useSoap12 = false;
			usesRPC = default;
			wsdlName = "";
			soapHeaders = null;
		)
		subtract(parameters: Subtract): SubtractResponse updating, webService, wsdlName = "subtract";
		webServicesMethodProperties
		(
			inputEncodingStyle = "";
			inputNamespace = "";
			inputUsesEncodedFormat = false;
			outputEncodingStyle = "";
			outputNamespace = "";
			outputUsesEncodedFormat = false;
			soapAction = "urn:JadeWebServices/CalculatorService/subtract";
			useBareStyle = false;
			useSoap12 = false;
			usesRPC = default;
			wsdlName = "subtract";
			soapHeaders = null;
		)
	)
	Multiply completeDefinition
	(
		documentationText
`
    This class was generated by Jade.
     Runtime Version: 6.3

     Changes to this class may cause incorrect behavior and will be lost if 
     the class is regenerated. `
	attributeDefinitions
		a:                             Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:a", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
		b:                             Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:b", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
	)
	MultiplyResponse completeDefinition
	(
		documentationText
`
    This class was generated by Jade.
     Runtime Version: 6.3

     Changes to this class may cause incorrect behavior and will be lost if 
     the class is regenerated. `
	attributeDefinitions
		multiplyResult:                Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:multiplyResult", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
	)
	Subtract completeDefinition
	(
		documentationText
`
    This class was generated by Jade.
     Runtime Version: 6.3

     Changes to this class may cause incorrect behavior and will be lost if 
     the class is regenerated. `
	attributeDefinitions
		a:                             Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:a", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
		b:                             Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:b", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
	)
	SubtractResponse completeDefinition
	(
		documentationText
`
    This class was generated by Jade.
     Runtime Version: 6.3

     Changes to this class may cause incorrect behavior and will be lost if 
     the class is regenerated. `
	attributeDefinitions
		subtractResult:                Real required, webService, wsdlName = "urn:JadeWebServices/CalculatorService/:subtractResult", _xmlType = "double	http://www.w3.org/2001/XMLSchema";
	)
	WebSession completeDefinition
	(
	)
	RootSchemaSession completeDefinition
	(
	)
	SCalculatorServicesClient completeDefinition
	(
	)
databaseDefinitions
	CalculatorServicesClientDb
	(
	databaseFileDefinitions
		"calculatorservicesclient";
	defaultFileDefinition "calculatorservicesclient";
	classMapDefinitions
		CalculatorServicesClient in "_usergui";
		GCalculatorServicesClient in "calculatorservicesclient";
		SCalculatorServicesClient in "_environ";
	)
_exposedListDefinitions
	CalculatorService version=6216, priorVersion=0, registryId="_WebServices_Consumer"
	(
		Add
		(
		)
		AddResponse
		(
		)
		Divide
		(
		)
		DivideResponse
		(
		)
		JadeCalculator
		(
		)
		Multiply
		(
		)
		MultiplyResponse
		(
		)
		Subtract
		(
		)
		SubtractResponse
		(
		)
	)
typeSources
	JadeScript (
	jadeMethodSources
testCalculator
{
testCalculator();

vars
	webService:			JadeCalculator;
	addRequest:			Add;
begin
	// set up the web service and the parameters for the add method call
	create webService;
	create addRequest;
	addRequest.a := 15;
	addRequest.b := 20;
	
    // now call the web service
	write webService.add(addRequest).addResult;

epilog
	delete webService;
	delete addRequest;
end;

}
	)
	JadeCalculator (
	jadeMethodSources
create
{
create() updating;

vars

begin
    logStatistics := true;
end;
}
getSoapAction
{
getSoapAction(methodName: String) : String;

vars
    meth:   Method;
begin
    meth := self.class.getMethod(methodName);
    
    if meth <> null then
        return meth.JadeWebServicesMethod.soapAction;
    else
        return null;
    endif;    
end;
}
invoke
{
invoke(inputMessage: String): String updating;

vars
	usernameToken:		JadeUsernameToken;
	wsAddress:			JadeWSAddressingHeader;
	wsTimestamp:		JadeWSTimestampHeader;
    out:    			String;
    str:    			StringUtf8;
    jwss: 				JadeWebServicesSecurity;

begin
    // add addressing information
	create wsAddress;
    wsAddress.action := getSoapAction('add').StringUtf8;
    wsAddress.sendTo := getEndpointURL.StringUtf8;
    str := wsAddress.getXml(inputMessage.StringUtf8);
   
	// add the timestamp header and set the expiry time to 1000
	create wsTimestamp;
	wsTimestamp.secondsToTimeout := 1000;
    str := wsTimestamp.getXml(str);
	
	// set up the user name token we will use the hased password
	create usernameToken;
	usernameToken.createDotNetObject_1("wilbur", "password", usernameToken.PasswordOption_SendHashed, 
										usernameToken.EncodingType_Base64Binary);
    
    usernameToken.protectionOrder := Jadwssec.ProtectionType_SignAndEncrypt;
	usernameToken.clearPassword := "password"; //password for signing end encryption
    
    str := usernameToken.getXml(str);
    
    // now send the message by calling the superclass method and wait for response 
    
    out := inheritMethod(str.String);
    
    // the out variable now contains the response message get the tokens and validate them. 
    
    create jwss;
    jwss.getTokens(out.StringUtf8);

    if jwss.addressing = null then
        raiseSecurityTokenException("Addressing header is missing");
    endif;
        
    if jwss.creationTimestamp = null then
        raiseSecurityTokenException("Timestamp security header is missing");
    endif;

    jwss.creationTimestamp.validateTimestamp();
    
    return out.String;
    
epilog
	delete usernameToken;
	delete wsAddress;
	delete wsTimestamp;

end;
}
	webServicesMethodSources
add
{
add(parameters:Add) : AddResponse webService, updating;


/*  This code was generated by Jade and cannot be modified
    Runtime Version: 6.3

*/

vars
	any: Any;
begin
	_methodName := method.name;

	addParameter("parameters", parameters);
	any := sendRequest("add");
	if any = null then 
		return null;
	else 
		return any.AddResponse;
	endif;
end;
}
divide
{
divide(parameters:Divide) : DivideResponse webService, updating;


/*  This code was generated by Jade and cannot be modified
    Runtime Version: 6.3

*/

vars
	any: Any;
begin
	_methodName := method.name;

	addParameter("parameters", parameters);
	any := sendRequest("divide");
	if any = null then 
		return null;
	else 
		return any.DivideResponse;
	endif;
end;
}
multiply
{
multiply(parameters:Multiply) : MultiplyResponse webService, updating;


/*  This code was generated by Jade and cannot be modified
    Runtime Version: 6.3

*/

vars
	any: Any;
begin
	_methodName := method.name;

	addParameter("parameters", parameters);
	any := sendRequest("multiply");
	if any = null then 
		return null;
	else 
		return any.MultiplyResponse;
	endif;
end;
}
raiseSecurityTokenException
{
raiseSecurityTokenException(msg: String) webService;

vars
    securityTokenException: Exception;
begin
    create securityTokenException;
    securityTokenException.errorCode := 5000;
    securityTokenException.extendedErrorText := msg;
    
    raise securityTokenException;
end;
}
subtract
{
subtract(parameters:Subtract) : SubtractResponse webService, updating;


/*  This code was generated by Jade and cannot be modified
    Runtime Version: 6.3

*/

vars
	any: Any;
begin
	_methodName := method.name;

	addParameter("parameters", parameters);
	any := sendRequest("subtract");
	if any = null then 
		return null;
	else 
		return any.SubtractResponse;
	endif;
end;
}
	)
